services:
  db:
    image: postgres:latest
    container_name: honadb
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./db_data:/var/lib/postgresql/data
volumes:
  db_data: